# Generated by Django 4.2.4 on 2023-09-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='reponse',
            field=models.CharField(default='VotreValeurParDefaut', max_length=255),
        ),
        migrations.AlterField(
            model_name='demande',
            name='demande_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Pending', 'Pending')], max_length=15),
        ),
    ]
