# Generated by Django 4.2.4 on 2023-09-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0003_demande_reponse_alter_demande_demande_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='reponse',
        ),
        migrations.AddField(
            model_name='demande',
            name='reponse_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
