# Generated by Django 4.2.4 on 2023-09-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0004_remove_demande_reponse_demande_reponse_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='reponse_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
