# Generated by Django 4.2.4 on 2023-09-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0006_rename_reponse_title_demande_repons_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='reponse_employe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
